### PR TITLE
Expand on installation, update DESCRIPTION, add renv

### PR DESCRIPTION
**Pull request by brookslogan**
This expands on the installation instructions in the index/preface.
- Main instructions now use `pak` rather than `remotes`.  `pak` takes half a minute to install, but is supposed to give better version set resolutions, sanity checks, and error messages than `remotes`.
- Main instructions now install more packages.  [So they can run (hopefully) all the sample code.]
- Supplementary information now suggests trying an RSPM mirror or using renv.
  - I show using RSPM via mirror settings on the former because `rspm::enable()` doesn't recognize some distributions the mirror seems to work on (e.g., my Fedora system), and `rspm::renv_init()` doesn't give good feedback in this setting.
  - To support the latter, renv-related files have been added to the repo.  Hopefully this won't annoy too many users that have renv troubles --- I'm guessing that copy-pasting from the book's web site would be more common than cloning/downloading the repo and starting an R session there --- but the renv.lock also points to RSPM mirrors, which will hopefully solve some issues of people with ancient compilers.
- The DESCRIPTION file Imports/Suggests have been updated.

### CODE REVIEW

**Comment by brookslogan** [comment]
The whole remotes vs. pak vs. renv (vs. pacman used by epirhandbook) is pretty bewildering.
- First three beat the last one in terms of maintenance last time I checked, but the last one might be more familiar if people have looked at epirhandbook.
- pak is supposed to be more user-friendly than remotes.
- pak and renv maintain their own (individual) package caches.  Right now I'd actually try to use renv::install for everything so I can have everything in its cache.  But I'm not so sure about using it in the main installation instructions for everyone as it seems like it might be pretty distracting and require some clarifications.

**Comment by dajmcdon** [comment]
Agreed. I think that, we should avoid pointing to any of these extra packages unless users are having install problems with the standard pathways.

To me `remotes` is familiar because it's just the broken out components of `devtools`. I wish that the `pak` docs would explain **why** I should be using it.

Let me pull this locally and rebuild. Maybe worth brainstorming a way to provide these somewhere, but not front and centre.

**Comment by brookslogan** [comment]
I didn't realize `quarto_preview()` didn't try to compile everything.  There are a few DESCRIPTION + renv + installation updates needed.

**Comment by brookslogan** [comment]
Okay, hopefully with these extra packages everything actually runs.

> Maybe worth brainstorming a way to provide these somewhere, but not front and centre.

Definitely.  My current approach (maybe not very clear from just "Files changed") is that the current RSPM & ~remotes~ renv stuff is folded inside a `<details>`, so people would actually have to click on a label to show this content.  That seemed easier/better than any sort of hyperlink-based solutions I could think of initially.

**Review by dajmcdon — APPROVED** [review]

**Pull request merged**
